### ISSUE TITLE
	[macOS] [CodeBox] Margin is missing in all code boxes and Copy button overlaps when long code is displayed.

### ISSUE THREAD

**Issue by DennyPerez18** [unoplatform/Uno.Gallery#133]
## Current behavior

![Screen Shot 2021-02-06 at 6 56 41 PM](https://user-images.githubusercontent.com/38770890/107132775-e5dd8e80-68af-11eb-8270-b2f48b7ce122.png)

## Expected behavior

<img width="995" alt="Capture8" src="https://user-images.githubusercontent.com/38770890/107132784-f2fa7d80-68af-11eb-89c6-927675a30b59.PNG">

## How to reproduce it (as minimally and precisely as possible)
1. Display any CodeBox
2. Ex. Select Overview from the left menu
3. Click on View component from TexBox section
4. Scroll on the page and expand the code from Multiline section
5. Notice the margin is missing and the Copy button overlaps the code 

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] macOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renders for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [x] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
## Investigations
* The problem seems occur when the `<TextBlock />` is forced to wrap because there's not enough available horizontal space to render the text.
* As soon there's not enough space for the text in the layout, the margins seems to dissapear and sometimes the content could be duplicated.
* The triggerring of the duplicated content is still unknown, but when it's happening, the text element is only present once in the managed visual tree (as we can see with `.ShowLocalVisualTree()`).

**Comment by carldebilly** [comment]
This issue won't be fixed for 3.5.  In the mean time, we can use a work-around: use narrower text. The bug is happening when the text is wider than the available space.
