### ISSUE TITLE
[Neumorphism][Light Theme] Filled Button shadow issues

### ISSUE THREAD

**Issue by kazo0** [unoplatform/Uno.Gallery#912]
**Buttons (Light Theme only)**

Happens at the very least on WASM, probably other Uno platforms as well

Top left Shadow seems to be missing in the implementation of enabled filled buttons
and too large in the disabled states
Implemented
![image](https://github.com/unoplatform/Uno.Gallery/assets/29584087/86fe2116-2a5f-488c-b8da-297db135246b)

Expected
![image](https://github.com/unoplatform/Uno.Gallery/assets/29584087/969d355b-57f9-48c6-a4b4-2189b719d5e5)

_Originally posted by @NVLudwig in https://github.com/unoplatform/Uno.Gallery/issues/903#issuecomment-1692331870_

**Comment by agneszitte** [comment]
@eriklimakc if you can please take a quick look to make sure we are not missing something obvious for the shadowscollection here please

**Comment by eriklimakc** [comment]
So we are following the right shadows from figma for the Buttons, except for the Disabled state as it didn't give us the expected result.

Something we can do to improve the visibility of the shadows on **Normal, Hovered, Focused** VisualStates is increase the Opacity of the Light shadow to 0.6/0.7/0.7

For the disabled VisualState I went into it to find the problem, and as I can see, since we're using a Color Brush with 8% of transparency the shadows were visible under the background, which gives us the weird result. I quickly tested adding a `<Grid>` as State Layer and set the Brush to it instead to the main `<Grid>` and got this result:

![image](https://github.com/unoplatform/Uno.Gallery/assets/114886335/f096bbdf-4092-4cdc-8b2c-046665985a43)

### Do you think it's a better result?

cc @Arieldelossantos @agneszitte @NVLudwig

**Comment by NVLudwig** [comment]
Still off but yes it's getting better

**Comment by Arieldelossantos** [comment]
i'm working on it and will create a PR soon

**Comment by agneszitte** [comment]
Re-Open to check the status of #923

**Comment by agneszitte** [comment]
Will be fixed with https://github.com/unoplatform/Uno.Gallery/pull/992
