### ISSUE TITLE
[Gallery][iOS/Android][CheckBox] Wrong initial Foreground color for the text in the sample pages

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/Uno.Gallery#940]
## Current behavior

For Android and iOS, the initial foreground colors are off for CheckBox (matching Fluent apparently as it is the same resource name), so for Android and iOS the override for re-initializing MaterialTheme as part of the MaterialTemplate does not seem to work properly.

(note the checkbox header font color)
![image](https://github.com/unoplatform/Uno.Gallery/assets/16295702/b05aabd5-c40a-45b3-aab2-b7de1ccb2fa9)

## Expected behavior

On Windows, Wasm, Skia.GTK, we have this expected result (note the proper font color of the CheckBox):
![image](https://github.com/unoplatform/Uno.Gallery/assets/16295702/a250963d-83ba-42ff-b14a-4684d47ce4bb)

## How to reproduce it (as minimally and precisely as possible)

- Launch Gallery sample app
- Noticed the Foreground color of the text for CheckBox on the main Overview page.

## Environment

All latest packages (Uno + Uno.Material)

Affected platform(s):

- [X] iOS
- [X] Android

### Issue-specific to Gallery setup at the moment - we are not yet able to reproduce it on a sample app

- The interesting thing is once you check/uncheck the CheckBox, the colors correct themselves. So there is something off with the initial resolution of the Foreground color for the ContentPresenter. We did notice that the foreground colors for other controls like RadioButton work fine and we see that the difference here is that the RadioButton's ContentPresenter does not have the `Foreground="{TemplateBinding Foreground}"` set on it as the CheckBox does. 
So there may be some sort of timing issue between when the resources are resolved and when the Foreground is actually set on the ContentPresenter?

- Looks like any property that is template-bound doesn't get the overridden value on the initial load. So even setting `CheckBoxBackgroundUnchecked` to Purple results in the checkbox initially staying at the Fluent value of Transparent until I check and then uncheck the CheckBox, then it becomes purple:
 
  On initial load:
  ![image](https://github.com/unoplatform/Uno.Gallery/assets/16295702/410d4278-4099-4d6a-9c77-065811d973de)

  After checking and unchecking:
  ![image](https://github.com/unoplatform/Uno.Gallery/assets/16295702/f8c84fdc-00ca-4450-95ba-1565e1d1653b)

- And finally, we also noticed that if we switch the Material resources to be last in App.xaml the issue is not there
![image](https://github.com/unoplatform/Uno.Gallery/assets/16295702/45578434-4931-4f5e-a739-16824034d6bd)

**Comment by jeromelaban** [comment]
What's the impact of setting material last?

**Comment by agneszitte** [comment]
> What's the impact of setting material last (other than working around the issue)?

cc @kazo0, @Xiaoy312

**Comment by Xiaoy312** [comment]
dont we always initialize XamlControlRsources first?
the obviously impact is the default control styles, since the last initialized library will contribute first
also didnt we went over this last time, and there are problem no matter which gets initialized last? either fluent style or material style is broken depending on the order.

**Comment by kazo0** [comment]
Two paths:

1. Material -> Fluent and then we re-init Material in the MaterialContentPresenter for the SamplePageLayout [here](https://github.com/unoplatform/Uno.Gallery/blob/9fb342c26e0648332eb0adfb62dd2be0b343d950/Uno.Gallery/Uno.Gallery.Shared/Views/Styles/SamplePageLayout.xaml#L214-L229) _**This is our current method**_
2. Fluent -> Material and then we re-init Fluent in the FluentContentPresenter for SamplePageLayout [here](https://github.com/unoplatform/Uno.Gallery/blob/9fb342c26e0648332eb0adfb62dd2be0b343d950/Uno.Gallery/Uno.Gallery.Shared/Views/Styles/SamplePageLayout.xaml#L231-L238)

With Option 1 we are re-initializing the lesser of two evils since I would assume MaterialToolkitTheme is less heavy than XamlControlsResources (right?). Downside is we aren't using Material by default for the styling of the outer shell of the application, so we may run into issues similar to what we originally had if we were to start using CheckBoxes/RadioButtons/etc. outside of just the sample areas.

With Option 2 we are re-initializing XamlControlsResources, which is probably pretty large. Although, it would probably be re-initialized less often as Material is usually the default tab to be loaded when opening up sample pages. Upside is that Material is the default styling for the entire application in this case

After doing a quick test, the problem we are seeing here is avoided if we initialize Material last (Option 2)

Material on page load
<img alt="image" src="https://github.com/unoplatform/Uno.Gallery/assets/4793020/362f37a2-be3b-4cc8-abaa-57da4448f020">

If I switch to Fluent
<img alt="image" src="https://github.com/unoplatform/Uno.Gallery/assets/4793020/b833d097-82ea-4e28-b469-de24093122e5">
